### PR TITLE
Code reformat

### PR DESCRIPTION
**Pull request by szszszsz**
Results of running `black` and `isort` over the code base. 
Waiting with merging until the current work is finished.

cc @daringer

### CODE REVIEW

**Comment by szszszsz** [comment]
Note: this is just an output example, no need to merge this specific PR

**Comment by robin-nitrokey** [comment]
> Waiting with merging until the current work is finished.

Is this still valid?  If we would fix the code formatting, we could add the linters to the CI.

**Comment by szszszsz** [comment]
> Is this still valid? If we would fix the code formatting, we could add the linters to the CI.

Yes, in general this would be nice to have, and allow to increase the code quality. We need to decide yet about the current maintenance issues we face with the project first. In case we would tighten the integration with the upstream, we might need them to use it too for the easy codebase merging.

**Comment by szszszsz** [comment]
The idea behind this PR is still current.

**Comment by robin-nitrokey** [comment]
Fixed with #103.

**Pull request closed without merging**
