### PR TITLE
Add basic support for managing Nitrokey 3 devices

### PR DESCRIPTION
**Pull request by robin-nitrokey**
This patch adds the nk3 subcommand that can be used to list and query
Nitrokey 3 devices.  Note that the wink command does not yet work with
firmware version 1.0.0.

### CODE REVIEW

**Review by szszszsz — APPROVED** [review]
LGTM

Nice, typed and clean implementation. In detail:
1. Good idea with Click.context
2. I think abstract class usage turned out to be redundant here
3. I wish part of the implementation would be testable with pytest for integration runs, e.g. getting version or uuid from the device, to verify the returned format and parsing.

**Comment by robin-nitrokey** [comment]
@szszszsz Thanks for the review!

> I think abstract class usage turned out to be redundant here

I know the base class is redundant here, but it will become useful once we add bootloader support.  (My first draft included that but I removed it for this PR, so it looks a bit incomplete.)

> I wish part of the implementation would be testable with pytest for integration runs, e.g. getting version or uuid from the device, to verify the returned format and parsing.

I tried to separate that logic from the CLI.  Wouldn’t it be possible to write these tests using the `pynitrokey.nk3` module?

**Comment by szszszsz** [comment]
> I tried to separate that logic from the CLI. Wouldn’t it be possible to write these tests using the pynitrokey.nk3 module?

Ah, that's right indeed. What I rather meant is, that we should start building some unit test database to make sure that we stay compatible with subsequent releases between device's firmware and pynitrokey's client.

**Review by daringer — APPROVED** [review]

**Comment by robin-nitrokey** [comment]
Thanks for the reviews!  I’ve addressed your comments and will merge now.

**Pull request merged**
