### PR TITLE
Get rid of libusbio

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**
Needs testing on windows and macos
edit: meissner hijacking this

* [ ] mac test confirmation (@mmerklinger )
* [x] linux nk3 in firmware
* [x] linux nk3 in bootloader still crashes (weird `hid` stuff I don't understand @daringer - fixed)
* [x] windows works (@jj-so )

### CODE REVIEW

**Review by jj-so — COMMENTED** [review]
Testing on Windows 11 was successful.

**Comment by daringer** [comment]
updated PR desc

**Comment by mmerklinger** [comment]
Tested on macOS 14 (ARM64). Listing and reading the version works. Then I attempted an update of the NK3. This fails, leaving the NK3 in bootloader mode. Running the update again returns the same error. Removing the forced two-step update process has the same outcome.

[nitropy_output.txt](https://github.com/user-attachments/files/15928226/nitropy_output.txt)
[nitropy.log.iymm54or.txt](https://github.com/user-attachments/files/15928231/nitropy.log.iymm54or.txt)

**Comment by daringer** [comment]
ah ok - the error on mac is the same as on linux:
```
230      WARNING pynitrokey.cli An unhandled exception occurred
Traceback (most recent call last):
  File "/Users/testuser/Projects/pynitrokey/venv/lib/python3.9/site-packages/pynitrokey/trussed/bootloader/lpc55_upload/utils/interfaces/device/usb_device.py", line 78, in open
    self._device = hid.device.open_path(self.path)
TypeError: descriptor 'open_path' for 'hid.device' objects doesn't apply to a 'bytes' object
```
quite obviously it is not using `hid.device` correctly....

**Comment by daringer** [comment]
works with lpc on linux for me now, @mmerklinger please check

**Comment by robin-nitrokey** [comment]
Replaced by:
- https://github.com/Nitrokey/pynitrokey/pull/553
- https://github.com/Nitrokey/nitrokey-sdk-py/pull/35

**Pull request closed without merging**
