### PR TITLE
Spsdk vendor

### LINKED ISSUE #512: nitropy - invalid module error with latest python cryptography module
Trying to update my nitrokey 3 firmware fails with:

```
command line tool to interact with Nitrokey devices 0.4.45
Critical error:
An unhandled exception occurred
        Exception encountered: ModuleNotFoundError("No module named 'cryptography.hazmat.backends.openssl.rsa'")
```

python-cryptography 42.0.5 installed, downgrading to 41 fixes the problem.

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**
Vendor parts of SPSDK needed for LPC55 updates.

Similar to https://github.com/Nitrokey/pynitrokey/pull/346

This is currently in a state that works (validating and uploading updates tested), but I can likely remove a lot of code and still keep it working. Ideally we don't need such a large blob.

spsdk is licensed BSD-3 clause, so it's compatible.

The goal is to fix #512

### CODE REVIEW

**Comment by robin-nitrokey** [comment]
Maintaining the fork in a separate repository that is forked from spsdk would make it easier to pull in upstream changes.  It could still be included as a submodule here so that we don’t need to release it separately.  What do you think?

**Comment by sosthene-nitrokey** [comment]
Would making it a separate project not bring packaging issues?

**Comment by daringer** [comment]
let's pull it in first, like `nrf_upload` - once we pull out the cli we should think how and if this should also be separate...

**Comment by sosthene-nitrokey** [comment]
I've been able to minimize it even more. This allowed removing the `gmssl` dependency. We are also rid of `pypemicro`.

**Comment by robin-nitrokey** [comment]
Regading mypy, are there still errors when disabling strict checks?

https://github.com/Nitrokey/pynitrokey/blob/a76b1b17e099bb65b6e321d97089275a2d47fea5/pyproject.toml#L83-L98

**Comment by sosthene-nitrokey** [comment]
There are still a couple of errors, but much less (36).

Maybe I can try to fix them.

**Comment by sosthene-nitrokey** [comment]
I've fixed the mypy errors in spsdk, bumped mypy to 1.9 and cryptography to 42.

**Comment by daringer** [comment]
`libusbsio` is another weird nxp package, which essentially just wraps hid, right ? 
would it make sense to take a look on removing that?

**Comment by sosthene-nitrokey** [comment]
libusbsio wraps a custom binary library by NXP. Ripping it off would be a bit more involved. We can't also check what this binary does since it's not open source (only its header are...).

This does mean it would be great to get rid of it though.

**Comment by sosthene-nitrokey** [comment]
We could indeed get it to work with just hidapi, the wrapper appears very thin.

**Comment by robin-nitrokey** [comment]
The tricky part with replacing libusbsio is testing on Windows and Mac.  I remember that we initially had some problems with the bootloader communication on other platforms than Linux so we should pay close attention not to accidentally break it with refactoring.

**Comment by robin-nitrokey** [comment]
Replaced by:
- https://github.com/Nitrokey/pynitrokey/pull/553 
- https://github.com/Nitrokey/nitrokey-sdk-py/pull/32.

**Pull request closed without merging**
