### PR TITLE
Add py.typed file

### PR DESCRIPTION
**Pull request by robin-nitrokey**
This patch adds a py.typed file so that users of the library can make use of our type annotations.

## Checklist

Make sure to run `make check` and `make fix` before creating a PR, otherwise the CI will fail.

- [x] tested with Python3.9
- [x] signed commits
- [ ] updated documentation (e.g. parameter description, inline doc, docs.nitrokey)
- [x] added labels

### CODE REVIEW

**Comment by szszszsz** [comment]
Hey! Can you link to proper the docs, so I could verify the PR?

**Comment by robin-nitrokey** [comment]
This is specified by [PEP 561](https://peps.python.org/pep-0561/).

**Comment by szszszsz** [comment]
Does it work for you? I think you are missing adding this file to the project configuration (which is suggested in the docs).

**Comment by robin-nitrokey** [comment]
Yes, it works for me.  We use `flit` for packaging and it includes all files inside the package folder:

> Data files which your code will use should go inside the Python package folder. Flit will package these with no special configuration.

https://flit.pypa.io/en/stable/pyproject_toml.html#external-data-section

Note that we don’t mention the `VERSION` file in there either.

**Review by daringer — APPROVED** [review]

**Review by szszszsz — APPROVED** [review]

**Pull request merged**
