### PR TITLE
Simplify dependency handling

### PR DESCRIPTION
**Pull request by robin-nitrokey**
This PR simplifies dependency handling by:
- introducing the `dev` extra for development dependencies,
- removing the `ci-dependencies.txt` and `dev-dependencies.txt` to avoid duplication and
- migrating the `pyproject.toml` to the standard PEP 621 format.

This means that we now (mostly) use standard metadata which makes us less dependent of a specific tool and that `pip` can now be used as a frontend, invoking `flit` internally, which makes the build process simpler and easier to understand.

To install `pynitrokey` and all of its runtime dependencies but no dev dependencies, you can now simply call:
```
$ pip install -e .
```
To include the dev dependencies, use this instead:
```
$ pip install -e .[dev]
```

This requires bumping the `flit` and `pip` versions, but both are still supporting Python 3.6.

### CODE REVIEW

**Review by szszszsz — APPROVED** [review]
LGTM. If it works for CI then let's merge it.

**Comment by robin-nitrokey** [comment]
> This requires bumping the flit and pip versions, but both are still supporting Python 3.6.

To be precise, it would require pip 21.3.1 which has not yet arrived in Debian stable or Ubuntu.  Does that mean we can’t ship this PR until newer pip versions are available in the distributions?

**Comment by szszszsz** [comment]
Interesting observation - I thought this was introduced last year already.
If that blocks the installation, and user is unable to update `pip` before doing so, then I think so, and we should not merge it yet unfortunately.

**Comment by robin-nitrokey** [comment]
Okay, then I’ll try to factor out those changes that have lower pip requirements.

**Comment by robin-nitrokey** [comment]
I’ve extracted the parts that work with older pip versions in #172 and #174.  The only thing that is missing is directly using `pip install -e .[dev]` in the Makefile because it would require a newer pip version, but it’s not too important either.

**Pull request closed without merging**
