### PR TITLE
Add libusbsio DLLs to Windows build script

### PR DESCRIPTION
**Pull request by robin-nitrokey**
Fixes https://github.com/Nitrokey/pynitrokey/issues/170

This is reported to fix the `nitropy.exe`.  @daringer Can you please test it on your system and also check whether the installer works?

### CODE REVIEW

**Comment by szszszsz** [comment]
ping @daringer

**Comment by szszszsz** [comment]
I can't test it at the moment due to packaging issues. This is what I get while trying to run the installer:
> nitropy.exe - System Error
> The code execution cannot proceed because python36.dll was not found. Reinstalling the program may fix this problem.

If this is on my side only, please let me know how to fix it.

**Comment by szszszsz** [comment]
Does not work built from this branch - complaining about missed `spsdk` modules.
Rebasing and  trying again in `fix-dlls-rebased`. Leaving this branch intact for now.


screen

For comparison: current build v0.4.16, without the fix
no fix

**Comment by robin-nitrokey** [comment]
> Does not work built from this branch - complaining about missed spsdk modules.

That is expected due to the [incompatible spsdk 1.6.0 release](https://github.com/Nitrokey/pynitrokey/pull/180#issuecomment-1031209339).

**Comment by szszszsz** [comment]
Works after the rebase! Looks good to me.
I run the update, and it finished under 10 seconds. `nk3 test` passes too. 
Anything else worth checking before merging?

**Comment by robin-nitrokey** [comment]
Did you test the installer, the binary or both?

>  Anything else worth checking before merging?

No, not from my side.

**Comment by szszszsz** [comment]
Single binary only. Did not touch the installer. I did not see any changes in this regard in code - shall I look into it anyway?

**Comment by robin-nitrokey** [comment]
No, just wanted to know whether it magically repaired itself after your last report.

**Comment by szszszsz** [comment]
Ok! Will check it then on the next release.

**Pull request merged**
